tunnel: c59d0882-668b-493e-823b-7ce232ab4210
credentials-file: /etc/cloudflared/creds/c59d0882-668b-493e-823b-7ce232ab4210.json
ingress:
  - hostname: api.waterbase.click
    service: http://backend-nginx-1:80
  - hostname: www.waterbase.click
    service: http://backend-nginx-1:80
  - service: http_status:404
